Repository schiltz3/The-DMs-Toolkit, pull requests merged in 2022-11, with the labels that each got.

#151 fix spelling
  toolkit/templates/confirm_account_creation.html
Labels: Bug

#138 Swap to using row/col for char page
  toolkit/templates/character_generator.html
Labels: Enhancement

#154 Schiltz3/proficiency
  toolkit/templates/character_generator.html
  toolkit/views/character_generator/character_generation.py
  toolkit/views/character_generator/character_generator.py
Labels: Code

#175 Schiltz3/nav bar changes
  toolkit/static/custom.css
  toolkit/templates/elements/bar.html
Labels: Bug, Enhancement

#189 Swap from `+` to f-string
  toolkit/models.py
Labels: Bug

#190 Rework other strs
  toolkit/models.py
Labels: Enhancement

#191 Schiltz3/save character
  thedmstoolkit/settings.py
  toolkit/admin.py
  toolkit/migrations/0010_savecache.py
  toolkit/migrations/0011_alter_savecache_character.py
  toolkit/migrations/0012_rename_savecache_cache.py
  toolkit/models.py
  toolkit/templates/character_generator.html
  toolkit/templates/elements/messages.html
  toolkit/views/character_generator/cache_character.py
  toolkit/views/character_generator/character_elements.py
  toolkit/views/character_generator/character_generator.py
Labels: Enhancement, Database, User, Code

#195 lvl1
  toolkit/views/character_generator/cache_character.py
Labels: Bug

#196 Schiltz/arrange stats
  Tests/test_Character_Creation_UNIT.py
  toolkit/views/character_generator/character_generation.py
  toolkit/views/character_generator/character_generator.py
Labels: Code

#200 remove user and session
  databases/loot.json
Labels: Bug

#202 Character Gen Bugs
  thedmstoolkit/settings.py
  toolkit/views/character_generator/character_generator.py
Labels: Bug

#206 Fix armor cache list
  toolkit/views/loot_generator/loot_generator.py
Labels: Bug

#212 Schilez3/rename files
  Tests/test_Character_Creation_UNIT.py
  Tests/test_Encounter_Generation_UNIT.py
  Tests/test_Loot_Generation_UNIT.py
  Tests/test_create_account.py
  Tests/test_create_account_UNIT.py
  Tests/test_loot_generator.py
  thedmstoolkit/urls.py
  toolkit/utilities/__init__.py
  toolkit/utilities/cache.py
  toolkit/views/account/__init__.py
  toolkit/views/account/confirm_account_creation.py
  toolkit/views/account/create_account.py
  toolkit/views/account/login.py
  toolkit/views/account/logout.py
  toolkit/views/character_generator/cache_character.py
  toolkit/views/character_generator/character_elements.py
  toolkit/views/character_generator/character_generator_backend.py
  toolkit/views/character_generator/character_generator_view.py
  toolkit/views/encounter_generator/encounter_generator_backend.py
  toolkit/views/encounter_generator/encounter_generator_view.py
  toolkit/views/loot_generator/cache_loot.py
  toolkit/views/loot_generator/loot_generator_backend.py
  toolkit/views/loot_generator/loot_generator_view.py
  toolkit/views/saved/__init__.py
  toolkit/views/saved/saved_characters.py
  toolkit/views/saved/saved_encounters.py
  toolkit/views/saved/saved_loot.py
Labels: Enhancement

#213 hehe
  thedmstoolkit/urls.py
  toolkit/templates/login.html
  toolkit/templates/reset_password.html
  toolkit/views/account/change_password.py
  toolkit/views/account/reset_password.py
Labels: Enhancement

#218 no more + 0
  toolkit/views/character_generator/character_elements.py
Labels: Enhancement

#225 generate cache if it does not exist
  toolkit/models.py
Labels: Bug
