Repository schiltz3/The-DMs-Toolkit, pull requests merged in 2022-10, with the labels that each got.

#101 use username rather than email and set as default value
  toolkit/templates/login.html
  toolkit/views/create_account.py
Labels: Bug, Create User, Login, User

#104 add-quotes
  toolkit/templates/character_generator.html
Labels: Bug

#127 deepsource is still mad
  toolkit/views/character_generator/character_generator.py
Labels: Bug

#128 Tentatively Done without more advice
  Tests/test_Character_Creation_UNIT.py
  Tests/test_Loot_Generation_UNIT.py
  thedmstoolkit/loot_generation.py
  toolkit/views/character_generator/character_generation.py
Labels: Enhancement

#130 Schiltz/char gen improvements
  toolkit/templates/character_generator.html
  toolkit/views/character_generator/character_generator.py
Labels: Enhancement

#142 Schiltz3/logging and exceptions
  thedmstoolkit/settings.py
  toolkit/views/loot_generator/loot_generation.py
  toolkit/views/loot_generator/loot_generator.py
Labels: Enhancement
